all:shell

shell: shell.c parse.c run_command.c is_background.c builtin.c pipe_command.c pipe_present.c redirect_in.c redirect_out.c
	gcc -Wall shell.c parse.c run_command.c is_background.c builtin.c pipe_command.c pipe_present.c redirect_in.c redirect_out.c -o myshell
