all:hostinfo mydate printdir mycat pipe_ls

hostinfo:hostinfo.c
	gcc -Wall hostinfo.c -o hostinfo
mydate:mydate.c
	gcc -Wall mydate.c -o mydate
printdir:printdir.c
	gcc -Wall printdir.c -o printdir
mycat:mycat.c
	gcc -Wall mycat.c -o mycat
pipe_ls:pipe_ls.c
	gcc -Wall pipe_ls.c -o pipe_ls
